# Workflow to check if a user has correctly signed the CLA

name: Check Signed

on: 
  issue_comment:

  push:

jobs:
  check-signed:
    name: Check CLA signed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: dfinity/repositories-open-to-contributions
      - name: Debug
        run: |
          ls -a
      - name: Check CLA issue
        uses: ./.github/actions/check_cla_issue/
